#!/usr/bin/env python3
"""Retag batch_07.json according to tagging rules."""

import json
import re

# Noise tags to remove
NOISE_TAGS = {
    "was", "now", "time", "model", "models", "data", "code", "library", "paper",
    "ai", "new", "use", "using", "used", "one", "like", "make", "way", "can",
    "also", "well", "even", "much", "many", "get", "got", "think", "good",
    "great", "best", "better", "want", "need", "see", "look", "go", "going",
    "work", "working", "people", "thing", "things", "really", "actually",
    "still", "without", "every", "thought", "something", "based", "take",
    "different", "point", "first", "last", "next", "will", "would", "could",
    "years", "year", "example", "interesting", "building", "just", "very",
    "know", "lot", "part", "open-source", "open", "source", "no", "build",
    "project", "us", "top", "fast", "early", "simple", "find", "stop",
    "install", "pip", "bash", "git", "conda", "torch", "deep", "modern",
    "rest", "http", "url", "svg", "badge", "pypi", "dev", "page", "tool",
    "tools", "science", "docs", "documentation", "framework", "community",
    "team", "server", "client", "language", "languages", "processing",
    "version", "release", "support", "system", "systems", "learning",
    "training", "trained", "train", "inference", "performance", "efficient",
    "efficiency", "scalable", "large-scale", "high-performance", "zero",
    "full", "built", "run", "running", "app", "apps", "with", "from",
    "into", "their", "for", "the", "an", "in", "on", "batch", "memory",
    "design", "note", "notes", "repo", "repository", "codebase",
    "packages", "package", "module", "modules", "scripts", "script",
    "files", "file", "config", "configuration", "hit", "good",
    "no", "yes", "us", "go", "bi", "x", "ds", "log", "logs", "readme",
    "dataset", "datasets", "fast", "pypi", "dev", "page", "cpu",
    "crate", "build", "built", "run", "running", "app", "apps",
    "apache", "index",
    "2024", "2025", "2026", "art", "quick", "quick-start",
    "hot", "demo", "demos", "widget", "preview",
}

# Personal tags to remove
PERSONAL_TAGS = {"raphaelsty", "raphaelsrty", "discute-avec-raphael", "raphael"}

# Source-type tags to remove
SOURCE_TAGS = {
    "twitter", "hackernews", "arxiv-doc", "arxiv", "jupyter-notebook",
    "bookmarks", "github", "blog-post", "blog", "hugging face", "huggingface",
    "hub", "paper", "papers", "pdf",
}

# Computer-science category tags (too generic, auto-generated by arxiv)
CS_CATEGORY_PREFIXES = (
    "computer science - ",
    "computer-science---",
)

# Additional noise to catch after normalization
EXTRA_NOISE = {
    'svg', 'badge', 'url', 'http', 'https', 'html', 'css',
    'no', 'yes', 'us', 'go', 'c', 'bi', 'x', 'ds', 'hit',
    'pdf', 'log', 'logs', 'readme',
    'now', 'fast', 'pypi', 'dev', 'good', 'early',
    'source', 'science', 'dataset', 'datasets',
    'hugging-face', 'huggingface', 'hugging-face',
    'install', 'pip', 'bash', 'git', 'conda',
    'torch', 'deep', 'modern', 'rest', 'page',
    'zero', 'full', 'make', 'built', 'run',
    'running', 'app', 'apps', 'files', 'file',
    'batch', 'memory', 'design', 'scripts', 'script',
    'repo', 'repository', 'codebase',
    'server', 'client', 'community', 'team',
    'system', 'systems', 'framework', 'documentation',
    'docs', 'version', 'release', 'support',
    'efficient', 'efficiency', 'scalable', 'large-scale',
    'high-performance', 'simple', 'find',
    'training', 'trained', 'train', 'inference',
    'performance', 'language', 'languages', 'processing',
    'twitter-data', 'twitter-api', 'policy-agent',
    'cpu', 'crate', 'document-screenshot', 'screen',
    'question-answering', 'functions', 'desktop', 'android', 'ios',
    'apache', 'index', 'notes', 'slides', 'website',
    'la-javaness', 'vision-reward-model',
    'computational-science', 'computer-science',
    'reward',
    'project', 'art', 'quick', 'quick-start',
    'topic', 'topics', 'node', 'nodes',
    'key', 'keys', 'value', 'values', 'object', 'objects',
    'abstract', 'format', 'formats', 'type', 'types',
    'class', 'classes', 'function', 'functions',
    'method', 'methods', 'struct', 'attribute',
    'interface', 'protocol',
    # Too generic or abbreviations
    'search', 'ir', 'kd', 'df', 'os', 'ci', 'cd',
    # Model size descriptors (noise without context)
    '7b', '13b', '70b', '8b', '3b', '1b',
    # Misc noise
    'robot',  # normalize to 'robotics' instead
    'recommender',  # use 'recommender-system' instead
    'strategies',  # too generic
    'convert',  # too generic
    'encoder',  # too generic
    'dense',  # too generic
    'offline',  # too generic alone
    'pipeline',  # too generic
    'manager',  # too generic
    'collection',  # too generic
    'syntax',  # too generic
    'grammar',  # too generic in most contexts
    'components',  # too generic
    'framework',  # already in NOISE_TAGS
    'algorithm',  # too generic
    'neural',  # use 'neural-network' instead
    'text',  # too generic
    'google',  # company name noise
    'meta',  # company name noise
    'generative',  # too generic alone (use 'image-generation' etc.)
    'awesome',  # curated list tag, too generic
    'quickly',  # noise
    'hacker',  # noise
    'help',  # noise
    'logo',  # noise
    'laws',  # use 'scaling-laws' instead
    'tags',  # noise
    'full-training-set',  # noise (appears in a wrong context)
    'merge',  # too generic
    'weights',  # too generic
    'recipe',  # noise
    'automatic',  # noise
    'monitoring',  # too generic
    'educational',  # noise
    'teaching',  # noise
    'web',  # too generic alone
    'engine',  # too generic
    'dependencies',  # too generic
    'document',  # too generic
    'documents',  # too generic
    'decoder',  # too generic
    'state-of-the-art',  # marketing noise
    'sota',  # same
    'distributed',  # use 'distributed-training' instead
    'policy',  # too generic alone
    'transformers',  # ambiguous: library vs architecture
    'vectors',  # use 'embeddings' or 'vector-search'
    'image',  # too generic
    'visual',  # too generic
    'vision',  # too generic alone
    'analysis',  # too generic
    'analytics',  # too generic
    'development',  # too generic
    'software',  # too generic
    'generation',  # too generic
    'modeling',  # too generic
    'transfer',  # too generic
    'matching',  # too generic
    'parallel',  # too generic
    'query',  # too generic
    'tokens',  # too generic
    'tuning',  # use 'fine-tuning' instead
    'task',  # too generic
    'tech',  # too generic
    'backend',  # too generic
    'cloud',  # too generic
    'hardware',  # too generic
    'storage',  # too generic
    'incremental',  # too generic
    'knowledge',  # too generic alone
    'context',  # too generic alone
    'feedback',  # too generic
    'sparse',  # too generic alone (use 'sparse-retrieval')
    'contrastive',  # use 'contrastive-learning' instead
    'supervised',  # too generic
    'bindings',  # too generic
    'plugin',  # too generic
    'extension',  # too generic
    'profile',  # too generic
    'profiles',  # too generic
    'matrix',  # too generic
    'graph',  # too generic
    'table',  # too generic
    'tables',  # too generic
    'mobile',  # too generic alone
    'native',  # too generic
    'local',  # too generic
    'chat',  # too generic
    'assistant',  # too generic alone
    'automation',  # too generic
    'evaluation',  # too generic
    'benchmarks',  # use 'benchmark' instead
    'experiments',  # too generic
    'experiment',  # too generic
    'concepts',  # too generic
    'course',  # too generic
    'tutorial',  # too generic
    'survey',  # too generic
    'hints',  # too generic
    'interview',  # too generic
    'prototyping',  # too generic
    'machine',  # too generic
    'notation',  # too generic
    'explore',  # too generic
    'actions',  # too generic
    'adapter',  # too generic
    'indexing',  # too generic
    'hooks',  # too generic
    'discord',  # platform noise
    'hacktoberfest',  # event noise
    'cargo',  # build tool noise
    'yaml',  # config format noise
    'json',  # data format noise
    'sql',  # too broad
}


def normalize_tag(t):
    """Normalize a tag: lowercase, replace spaces with hyphens."""
    if not t or not isinstance(t, str):
        return ""
    t = t.strip().lower()
    t = re.sub(r'\s+', '-', t)
    # Remove trailing/leading hyphens
    t = t.strip('-')
    # Fix common typos
    t = t.replace('gtp-', 'gpt-')
    t = t.replace('reinfocement', 'reinforcement')
    t = t.replace('information-extration', 'information-extraction')
    t = t.replace('knwoledge-distillation', 'knowledge-distillation')
    t = t.replace('knwoledge', 'knowledge')
    # Normalize common aliases
    aliases = {
        'machine-learning': 'ml',
        'machine learning': 'ml',
        'ml-framework': 'ml',
        'large-language-model': 'llm',
        'large-language-models': 'llm',
        'llms': 'llm',
        'language-model': 'llm',
        'language-models': 'llm',
        'language model': 'llm',
        'natural-language-processing': 'nlp',
        'neural-networks': 'neural-network',
        'deep-neural-networks': 'neural-network',
        'reinforcement-learning': 'reinforcement-learning',
        'reinforcement learning': 'reinforcement-learning',
        'deep-learning': 'deep-learning',
        'deeplearning': 'deep-learning',
        'deep learning': 'deep-learning',
        'information retrieval': 'information-retrieval',
        'computer-vision': 'computer-vision',
        'fine-tuning': 'fine-tuning',
        'finetuning': 'fine-tuning',
        'pre-training': 'pre-training',
        'pretraining': 'pre-training',
        'multi-vector retrieval': 'multi-vector-retrieval',
        'multi-vector-retrieval': 'multi-vector-retrieval',
        'late interaction': 'late-interaction',
        'late-interaction': 'late-interaction',
        'knowledge distillation': 'knowledge-distillation',
        'knowledge-distillation': 'knowledge-distillation',
        'vector database': 'vector-database',
        'sentence-transformer': 'sentence-transformers',
        'sentence transformers': 'sentence-transformers',
        'retrieval-augmented-generation': 'rag',
        'retrieval': 'information-retrieval',
        # Normalize plural/variant forms
        'pretrained': 'pretrained-model',
        'pre-trained': 'pretrained-model',
        'pretrained-models': 'pretrained-model',
        'recommender-systems': 'recommender-system',
        'recommendation': 'recommender-system',
        'semantic-ids': 'semantic-id',
        'algorithms': 'algorithm',
        # Normalize embedding/vector variants
        'embedding': 'embeddings',
        'multi-vector': 'multi-vector-retrieval',
        # Normalize OS/language tags
        'mac': 'macos',
        'cpp': 'c++',
        'c-plus-plus': 'c++',
    }
    if t in aliases:
        t = aliases[t]
    return t


def is_noise(t):
    """Check if tag is noise."""
    t_norm = t.lower().strip()
    if not t_norm:
        return True
    if t_norm in NOISE_TAGS:
        return True
    if t_norm in PERSONAL_TAGS:
        return True
    if t_norm in SOURCE_TAGS:
        return True
    if t_norm in EXTRA_NOISE:
        return True
    # Remove slugified CS category tags
    for prefix in CS_CATEGORY_PREFIXES:
        if t_norm.startswith(prefix):
            return True
    # Remove very short tags that are meaningless
    if len(t_norm) <= 1:
        return True
    # Remove numeric-only tags
    if t_norm.isdigit():
        return True
    # Remove "openai", "google", "meta", etc. as pure company names unless specific
    # Keep: "gemini", "gpt", "llama" as they are specific models
    return False


def clean_tags(raw_tags, extra_tags):
    """Merge tags+extra-tags, normalize, remove noise, deduplicate."""
    all_raw = list(raw_tags) + list(extra_tags)
    seen = set()
    cleaned = []
    for t in all_raw:
        if not t or not isinstance(t, str):
            continue
        n = normalize_tag(t)
        if not n:
            continue
        if is_noise(n):
            continue
        if n in seen:
            continue
        seen.add(n)
        cleaned.append(n)
    return cleaned


def retag(url, doc):
    """Apply retagging rules to a document."""
    title = doc.get("title", "")
    summary = doc.get("summary", "")
    tags = doc.get("tags", [])
    extra = doc.get("extra-tags", [])

    cleaned = clean_tags(tags, extra)

    url_lower = url.lower()
    title_lower = title.lower()
    summary_lower = summary.lower()
    combined = title_lower + " " + summary_lower

    is_twitter = "x.com/" in url_lower or "twitter.com/" in url_lower
    is_arxiv = "arxiv.org" in url_lower
    is_huggingface = "huggingface.co" in url_lower
    is_github = "github.com" in url_lower
    is_hackernews = title_lower.startswith("hackernews ")

    tag_set = set(cleaned)

    # --- Robotics / Simulation ---
    if any(w in combined for w in ["lerobot", "so-101", "so101", "so-100", "so100"]):
        tag_set.add("lerobot")
    if any(w in combined for w in [" robot", "robotics", "manipulation", "actuator", "gripper",
                                    "embodied", "servo", "kinematics", "quadruped"]):
        tag_set.add("robotics")
    if any(w in combined for w in ["isaac", "mujoco", "sim2real", "sim-to-real", "isaaclab"]):
        tag_set.add("simulation")
    if any(w in combined for w in ["vision-language-action", "vla model", " vla ", " vla."]):
        tag_set.add("vla")
    # More specific VLA check from original tags
    if "vla" in [t.lower() for t in tags]:
        tag_set.add("vla")

    # --- Reinforcement Learning ---
    rl_phrases = ["reinforcement learning", "rl algorithm", "policy gradient", "reward function"]
    rl_words = ["grpo", "ppo"]  # short words - require word boundaries
    if (any(w in combined for w in rl_phrases) or
            any(re.search(r'\b' + w + r'\b', combined) for w in rl_words)):
        tag_set.add("reinforcement-learning")
    # Also from original tags
    if "reinforcement-learning" in [normalize_tag(t) for t in tags + extra]:
        tag_set.add("reinforcement-learning")
    if "diffusion" in combined and any(w in combined for w in ["policy", "score", "denoising", "flow matching"]):
        tag_set.add("diffusion")

    # --- Information Retrieval ---
    if any(w in combined for w in ["colbert", "pylate"]):
        tag_set.add("colbert")
        tag_set.add("information-retrieval")
    if "late interaction" in combined or "late-interaction" in combined:
        tag_set.add("late-interaction")
        tag_set.add("information-retrieval")
    if any(w in combined for w in ["text embedding", "text embeddings"]):
        tag_set.add("embeddings")
        tag_set.add("information-retrieval")
    if "embeddings" in combined and any(w in combined for w in ["retrieval", "search", "similarity"]):
        tag_set.add("embeddings")
    if any(w in combined for w in ["rerank", "reranking", "reranker", "cross-encoder", "listwise rank"]):
        tag_set.add("reranking")
    if any(w in combined for w in ["hnsw", "approximate nearest", "ann search"]):
        tag_set.add("vector-search")
    if "faiss" in combined:
        tag_set.add("vector-search")
    if any(w in combined for w in ["bm25", "inverted index", "tfidf", "tf-idf", "lexical search"]):
        tag_set.add("lexical-search")
    if any(w in combined for w in ["retrieval-augmented", "retrieval augmented generation"]):
        tag_set.add("rag")
    if "splade" in combined:
        tag_set.add("sparse-retrieval")
    if "multi-vector" in combined or "multivector" in combined:
        tag_set.add("multi-vector-retrieval")
    if "sentence-transformer" in combined or "sentence transformer" in combined:
        tag_set.add("sentence-transformers")
    if "mteb" in combined:
        tag_set.add("information-retrieval")
        tag_set.add("embeddings")

    # --- LLM / NLP ---
    if any(w in combined for w in ["large language model", "large-language-model",
                                    "encoder-decoder model", "language model"]):
        tag_set.add("llm")
    if "fine-tuning" in combined or "finetuning" in combined or "lora " in combined:
        tag_set.add("fine-tuning")
    if "contrastive learning" in combined or "contrastive loss" in combined:
        tag_set.add("contrastive-learning")
    if "tokenizer" in combined or "tokenization" in combined:
        tag_set.add("tokenization")
    if "dpo" in combined and ("preference" in combined or "alignment" in combined or "optimization" in combined):
        tag_set.add("dpo")
    if any(w in combined for w in ["chain-of-thought", "chain of thought", "reasoning model"]):
        tag_set.add("reasoning")
    if "multilingual" in combined or "cross-lingual" in combined:
        tag_set.add("multilingual")
    if any(w in combined for w in ["quantization", "quantize", "int8", "int4", "float8"]):
        tag_set.add("quantization")
    if "knowledge distillation" in combined:
        tag_set.add("knowledge-distillation")
    if any(w in combined for w in ["long context", "long-context", "context length", "context window"]):
        tag_set.add("long-context")
    if "uncertainty" in combined and "llm" in combined:
        tag_set.add("uncertainty-estimation")
    if "hallucination" in combined:
        tag_set.add("hallucination")

    # --- ML/Training ---
    if "pytorch" in combined and is_github:
        tag_set.add("pytorch")
    if any(w in combined for w in ["distributed training", "fsdp", "deepspeed"]):
        tag_set.add("distributed-training")
    if "flash attention" in combined or "flash-attention" in combined:
        tag_set.add("flash-attention")
    if any(w in combined for w in ["pre-training", "pretraining"]) and "nlp" not in combined:
        tag_set.add("pre-training")
    if "scaling law" in combined:
        tag_set.add("scaling-laws")

    # --- Computer Vision / Multimodal ---
    if any(w in combined for w in ["multimodal", "multi-modal", "vision language",
                                    "vision-language", "vlm", "vision-language model"]):
        tag_set.add("multimodal")
    if any(w in combined for w in ["image generation", "text-to-image"]):
        tag_set.add("image-generation")
    if (re.search(r'\bocr\b', combined) or
            "optical character recognition" in combined or
            "document understanding" in combined or
            "document parsing" in combined):
        tag_set.add("ocr")

    # --- Systems / Languages ---
    if "rust" in combined and is_github:
        tag_set.add("rust")
    if any(w in combined for w in ["cuda kernel", "triton kernel", "gpu kernel"]):
        tag_set.add("cuda")
    if "webassembly" in combined or "wasm" in combined:
        tag_set.add("webassembly")

    # --- Recommendation Systems ---
    if any(w in combined for w in ["recommender system", "recommendation system",
                                    "collaborative filtering", "semantic id"]):
        tag_set.add("recommender-system")

    # --- Databases ---
    if "sqlite" in combined and "vector" in combined:
        tag_set.add("vector-database")
    if "duckdb" in combined:
        tag_set.add("duckdb")
    if any(w in combined for w in ["vector search", "vector index", "vector database"]):
        tag_set.add("vector-database")

    # --- macOS tools ---
    if any(w in combined for w in ["macos", "mac app", "swift app", "macbook"]):
        tag_set.add("macos")

    # --- Twitter/HN content ---
    if is_twitter:
        # If almost no tags, add discussion
        useful_tags = tag_set - {"discussion", "announcement", "opinion"}
        if len(useful_tags) < 2:
            tag_set.add("discussion")
    if is_hackernews and not tag_set:
        tag_set.add("discussion")

    # Remove noise again
    final_tags = [t for t in tag_set if not is_noise(t)]

    # Deduplicate
    seen = set()
    deduped = []
    for t in sorted(final_tags):
        if t not in seen:
            seen.add(t)
            deduped.append(t)

    # Priority: keep domain-specific over generic
    priority_keywords = {
        "colbert", "pylate", "lerobot", "robotics", "rag", "information-retrieval",
        "embeddings", "reranking", "llm", "fine-tuning", "rust", "pytorch",
        "reinforcement-learning", "vla", "diffusion", "ocr", "multimodal",
        "late-interaction", "multi-vector-retrieval", "knowledge-distillation",
        "sentence-transformers", "sparse-retrieval", "vector-search",
        "recommender-system", "cuda", "distributed-training", "transformer",
        "reasoning", "multilingual", "contrastive-learning", "deep-learning",
        "neural-network", "vector-database", "duckdb", "pre-training",
        "flash-attention", "long-context", "tokenization", "quantization",
        "dpo", "rlhf", "nlp", "ml", "macos", "simulation", "vla",
        "image-generation", "scaling-laws", "lexical-search",
    }

    if len(deduped) > 6:
        priority = [t for t in deduped if t in priority_keywords]
        others = [t for t in deduped if t not in priority_keywords]
        deduped = sorted(set((priority + others)[:6]))

    # Add language tag if we have room and it's a github repo
    if is_github and len(deduped) < 6:
        lang_tags = ["python", "rust", "typescript", "javascript", "go",
                     "c++", "c", "java", "swift", "lua", "shell", "vue",
                     "html", "perl", "racket", "scala"]
        for lt in lang_tags:
            orig_lower = [t.lower() for t in tags]
            if lt in orig_lower and lt not in deduped:
                deduped.append(lt)
                deduped.sort()
                break

    # Ensure minimum 3 tags
    if len(deduped) < 3:
        if is_arxiv:
            if "llm" in combined or "language model" in combined:
                if "llm" not in deduped:
                    deduped.append("llm")
            if "retrieval" in combined:
                if "information-retrieval" not in deduped:
                    deduped.append("information-retrieval")
            if len(deduped) < 3:
                deduped.append("research")
        elif is_huggingface:
            if "/datasets/" in url_lower:
                if "dataset" not in deduped:
                    deduped.append("dataset")
            elif "/spaces/" in url_lower:
                if "demo" not in deduped:
                    deduped.append("demo")
            else:
                if "pretrained-model" not in deduped:
                    deduped.append("pretrained-model")
            if "lightonai" in url_lower or "lighton" in combined:
                if "lighton" not in deduped:
                    deduped.append("lighton")
            if len(deduped) < 3:
                if "huggingface" not in deduped:
                    deduped.append("huggingface")
        elif is_github:
            lang_tags = ["python", "rust", "typescript", "javascript", "go",
                         "c++", "c", "java", "swift", "lua", "shell", "vue", "html"]
            for lt in lang_tags:
                orig_lower = [t.lower() for t in tags]
                if lt in orig_lower and lt not in deduped:
                    deduped.append(lt)
                    break
            if len(deduped) < 3:
                if "open-source-tool" not in deduped:
                    deduped.append("open-source-tool")
            # Still need more tags - infer from content
            if len(deduped) < 3:
                content_lower = combined
                if any(w in content_lower for w in ["language model", "llm", "gpt", "bert",
                                                      "transformer", "attention"]):
                    if "llm" not in deduped:
                        deduped.append("llm")
                    elif "nlp" not in deduped:
                        deduped.append("nlp")
                elif any(w in content_lower for w in ["machine learning", "deep learning",
                                                       "neural network", "training", "trained",
                                                       "model training", "supervised learning",
                                                       "reward", "policy", "agent"]):
                    if "ml" not in deduped:
                        deduped.append("ml")
                elif any(w in content_lower for w in ["vector", "embedding", "similarity"]):
                    if "embeddings" not in deduped:
                        deduped.append("embeddings")
                elif "cli" in content_lower or "command" in content_lower:
                    if "cli" not in deduped:
                        deduped.append("cli")
                elif any(w in content_lower for w in ["database", "sql", "storage", "query"]):
                    if "database" not in deduped:
                        deduped.append("database")
        elif is_twitter:
            if len(deduped) < 2:
                deduped.append("discussion")
            if len(deduped) < 3:
                deduped.append("announcement")
        elif is_hackernews:
            if "discussion" not in deduped:
                deduped.append("discussion")
        else:
            if len(deduped) < 3:
                deduped.append("resource")

        deduped = sorted(set(deduped))

    # Final cap at 6
    deduped = sorted(set(deduped))[:6]

    return {
        "title": doc["title"],
        "summary": doc.get("summary", ""),
        "tags": deduped,
        "extra-tags": []
    }


def main():
    input_path = "/Users/raphael/Documents/github/knowledge/database/batch_07.json"
    output_path = "/Users/raphael/Documents/github/knowledge/database/batch_07_retagged.json"

    with open(input_path, "r") as f:
        data = json.load(f)

    result = {}
    for url, doc in data.items():
        result[url] = retag(url, doc)

    with open(output_path, "w") as f:
        json.dump(result, f, indent=2, ensure_ascii=False)

    print(f"Processed {len(result)} documents -> {output_path}")

    # Stats
    tag_counts = [len(doc["tags"]) for doc in result.values()]
    from collections import Counter
    c = Counter(tag_counts)
    print(f"Tag count distribution: {dict(sorted(c.items()))}")


if __name__ == "__main__":
    main()
