"""Enrich the curated Twitter-handle candidates with profile links,
identifiers, and stats — one candidate at a time.

Per candidate we want, ideally:
  • github handle + GitHub followers + bio + company + blog URL
  • huggingface username (validated)
  • google scholar user_id (from search result URL)
  • semantic scholar authorId + citationCount + hIndex
  • dblp pid
  • personal website
  • affiliation (from GitHub `company` or Sem Scholar `affiliations`)

Cost model (credits-conscious)
------------------------------
  • 1 Tavily search per candidate (depth: advanced, max_results=8).
  • GitHub, HuggingFace, Sem Scholar, DBLP: keyless free APIs.

False-positive guard
--------------------
We DON'T blindly trust a URL because it surfaced. For each extracted
handle, we hit its native API and check the platform-side display
name against the candidate name (token-overlap ≥ 0.5). When it fails,
the field is left empty — the user prefers "no source" over "wrong
source".

Output is written incrementally to data/people/enriched_candidates.tsv
so an interrupted run resumes from where it stopped.

Usage::

    TAVILY_API_KEY=... uv run python scripts/enrich_candidates.py
    TAVILY_API_KEY=... uv run python scripts/enrich_candidates.py --limit 5  # smoke test
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import sys
import time
import unicodedata
import urllib.parse
import urllib.request
from pathlib import Path

# Sources we care about extracting from search results, in priority
# order. Each entry: (domain_match, kind, path_regex_to_extract_id).
# Path regex captures group 1 = the identifier we'd store.
_DOMAIN_PATTERNS = [
    ("github.com", "github", re.compile(r"^/([A-Za-z0-9][A-Za-z0-9-]{0,38})/?$")),
    ("huggingface.co", "huggingface", re.compile(r"^/([A-Za-z0-9][A-Za-z0-9-_\.]{1,38})/?$")),
    (
        "scholar.google.com",
        "scholar",
        re.compile(r"^/citations.*?[?&]user=([A-Za-z0-9_\-]+)"),
    ),
    (
        "scholar.google.co",
        "scholar",
        re.compile(r"^/citations.*?[?&]user=([A-Za-z0-9_\-]+)"),
    ),
    # DBLP author "pid" path is the stable key
    ("dblp.org", "dblp", re.compile(r"^/pid/([^/]+/[^/.]+)")),
]

# Domains we always skip as "homepage" — they're profile sites we
# already capture under another column, social media, or low-trust
# wikis/aggregators that spam search results with autogenerated
# 'wiki pages' about prominent researchers.
_HOMEPAGE_SKIP = {
    "x.com",
    "twitter.com",
    "facebook.com",
    "instagram.com",
    "linkedin.com",
    "youtube.com",
    "tiktok.com",
    "reddit.com",
    "github.com",
    "huggingface.co",
    "scholar.google.com",
    "dblp.org",
    "arxiv.org",
    "semanticscholar.org",
    "researchgate.net",
    "wikipedia.org",
    "medium.com",
    "substack.com",
    "ycombinator.com",
    "news.ycombinator.com",
    "t.co",
    "bsky.app",
    # New: social / publishing platforms we don't want as "homepage".
    "threads.com",
    "threads.net",
    "mastodon.social",
    "openreview.net",
    # New: scraper / aggregator wikis that auto-generate fluff pages.
    "businessabc.net",
    "wikitia.com",
    "famousbirthdays.com",
    "everipedia.org",
    "paperswithcode.com",
}

_TAVILY_URL = "https://api.tavily.com/search"
_USER_AGENT = "knowledge-enrich/1.0 (+https://knowledge-web.org)"


# ────────────────────────────────────────────────────────────────────
# Name-similarity guard
# ────────────────────────────────────────────────────────────────────


def _norm_tokens(s: str) -> set[str]:
    """Lowercase, strip diacritics, split on non-alpha. Used for
    fuzzy name comparison so 'Yann LeCun' ≈ 'yann lecun' ≈ 'ylecun'
    via subset checks."""
    s = unicodedata.normalize("NFKD", s or "")
    s = "".join(c for c in s if not unicodedata.combining(c))
    s = re.sub(r"[^a-zA-Z]+", " ", s).lower()
    return {t for t in s.split() if len(t) >= 2}


def _names_match(candidate_name: str, platform_name: str | None) -> bool:
    """Strict-ish name match used as a verification gate for social
    profiles (GitHub, HuggingFace) where users typically display
    their full name.

    Two-token candidates (the common 'First Last' case) MUST share
    both tokens with the platform name — otherwise we'd accept
    'Mark Chen' ↔ 'Mark Codering'. For 3+ token names we require at
    least two of the candidate's tokens to appear, which handles
    middle initials and 'Dr.' prefixes.

    Empty platform_name short-circuits to True so we still accept
    accounts that legitimately don't expose a display name (very
    common on GitHub).
    """
    if not platform_name:
        return True
    a, b = _norm_tokens(candidate_name), _norm_tokens(platform_name)
    if not a or not b:
        return True
    shared = a & b
    if len(a) <= 2:
        return shared == a
    return len(shared) >= 2


def _academic_name_match(candidate_name: str, platform_name: str | None) -> bool:
    """Looser match for academic profiles (Sem Scholar, DBLP). Those
    routinely shorten authors to 'S. Bubeck' or 'I. J. Goodfellow',
    so a strict 'both tokens present' rule throws everyone out.

    Rule:
      • Last token of the candidate name must appear in the platform
        name (the surname).
      • AND the candidate's first-name initial must match an initial
        in the platform name (any token starting with that letter).

    'Mark Chen' vs 'M. Chen' → surname 'chen' ✓, first letter M ✓ → accept.
    'Mark Chen' vs 'Bo Chen' → surname 'chen' ✓, M vs B → reject.
    'Sebastien Bubeck' vs 'S. Bubeck' → surname 'bubeck' ✓, S ✓ → accept.
    """
    if not platform_name:
        return True
    a, b = _norm_tokens(candidate_name), _norm_tokens(platform_name)
    if not a or not b:
        return True
    # Pull last/first tokens from candidate in original order.
    cand_seq = re.findall(
        r"[a-zA-Z]+", unicodedata.normalize("NFKD", candidate_name).encode("ascii", "ignore").decode()
    )
    cand_seq = [t.lower() for t in cand_seq if len(t) >= 1]
    if len(cand_seq) < 2:
        return bool(a & b)
    first, last = cand_seq[0], cand_seq[-1]
    if last not in b:
        return False
    first_initial = first[0]
    # Platform-name initials: first letter of every token.
    plat_seq = re.findall(r"[a-zA-Z]+", unicodedata.normalize("NFKD", platform_name).encode("ascii", "ignore").decode())
    return any(t[0].lower() == first_initial for t in plat_seq if t)


# ────────────────────────────────────────────────────────────────────
# HTTP helpers
# ────────────────────────────────────────────────────────────────────


def _http_json(url: str, headers: dict | None = None, timeout: int = 20) -> dict | None:
    req = urllib.request.Request(url, headers={"User-Agent": _USER_AGENT, **(headers or {})})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            if r.status != 200:
                return None
            return json.loads(r.read().decode("utf-8", errors="replace"))
    except Exception:
        return None


def _http_status(url: str, timeout: int = 10) -> int:
    """HEAD-style probe; returns status code or 0 on failure."""
    req = urllib.request.Request(url, method="HEAD", headers={"User-Agent": _USER_AGENT})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return r.status
    except Exception as e:
        # urlopen raises on >=400; mine the code when present.
        return getattr(e, "code", 0) or 0


# ────────────────────────────────────────────────────────────────────
# Tavily search (credit-conscious — one call per candidate)
# ────────────────────────────────────────────────────────────────────


def tavily_search(query: str, api_key: str) -> list[dict]:
    """One advanced Tavily search. Returns the `results` list or []."""
    body = json.dumps(
        {
            "api_key": api_key,
            "query": query,
            "search_depth": "advanced",
            # 8 is plenty: GitHub, HF, Scholar, DBLP, and a few stray
            # blog / news entries that may carry the homepage.
            "max_results": 8,
            "include_answer": False,
            "include_raw_content": False,
        }
    ).encode("utf-8")
    req = urllib.request.Request(
        _TAVILY_URL,
        data=body,
        method="POST",
        headers={
            "User-Agent": _USER_AGENT,
            "Content-Type": "application/json",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            if r.status != 200:
                return []
            payload = json.loads(r.read().decode("utf-8", errors="replace"))
            return payload.get("results") or []
    except Exception as e:
        print(f"    ! tavily error: {e}")
        return []


def extract_identifiers(results: list[dict]) -> dict:
    """Scan Tavily result URLs for the profile identifiers we want.
    First match per platform wins.

    NOTE: we don't extract a "homepage" from Tavily — search results
    surface news articles, podcast pages, encyclopedic wikis, etc.
    that the candidate doesn't own. We only trust homepage URLs that
    come from the platforms themselves: GitHub `blog` field or
    Semantic Scholar `homepage` field.
    """
    found: dict[str, dict] = {}
    for r in results:
        url = (r.get("url") or "").strip()
        if not url:
            continue
        try:
            p = urllib.parse.urlparse(url)
        except Exception:
            continue
        netloc = p.netloc.lower()
        if netloc.startswith("www."):
            netloc = netloc[4:]
        for domain, kind, rx in _DOMAIN_PATTERNS:
            if not netloc.endswith(domain):
                continue
            if kind in found:
                continue
            m = rx.match(p.path + ("?" + p.query if p.query else ""))
            if not m:
                continue
            # Tighten GitHub: ignore reserved org/feature paths.
            if kind == "github" and m.group(1).lower() in {
                "about",
                "features",
                "pricing",
                "marketplace",
                "topics",
                "trending",
                "explore",
                "search",
                "settings",
                "login",
                "signup",
                "orgs",
                "issues",
                "pulls",
            }:
                continue
            found[kind] = {
                "id": m.group(1),
                "url": url,
                "snippet": (r.get("content") or "")[:200],
            }
            break
    return {"sources": found}


# ────────────────────────────────────────────────────────────────────
# Per-platform verification
# ────────────────────────────────────────────────────────────────────


def verify_github(login: str, candidate_name: str, candidate_twitter: str = "") -> dict | None:
    data = _http_json(
        f"https://api.github.com/users/{urllib.parse.quote(login, safe='')}",
        headers=({"Authorization": f"Bearer {os.environ['GITHUB_TOKEN']}"} if os.environ.get("GITHUB_TOKEN") else None),
    )
    if not data:
        return None
    gh_twitter = (data.get("twitter_username") or "").lower().lstrip("@")
    cand_tw = (candidate_twitter or "").lower().lstrip("@")
    # Hard rule: when GitHub exposes a Twitter username AND it
    # doesn't match the candidate's, this is somebody else with the
    # same name — reject regardless of how well the display name
    # matches.
    if gh_twitter and cand_tw and gh_twitter != cand_tw:
        return None
    # When GitHub's twitter matches the candidate's, accept without
    # needing the display name to match — it's a strong identity signal.
    if not (gh_twitter and cand_tw and gh_twitter == cand_tw):
        if not _names_match(candidate_name, data.get("name")):
            return None
    return {
        "login": login,
        "name": data.get("name") or "",
        "bio": (data.get("bio") or "").strip(),
        "company": (data.get("company") or "").strip(),
        "blog": (data.get("blog") or "").strip(),
        "followers": int(data.get("followers") or 0),
        "avatar": data.get("avatar_url") or "",
    }


def verify_huggingface(username: str, candidate_name: str) -> dict | None:
    # HF's public user-overview endpoint. Returns minimal JSON when
    # the user exists, 404s otherwise.
    data = _http_json(f"https://huggingface.co/api/users/{urllib.parse.quote(username, safe='')}/overview")
    if not data:
        # Fall back to a HEAD on the profile page — if it 200s we
        # accept the username but skip verification.
        status = _http_status(f"https://huggingface.co/{username}")
        if status != 200:
            return None
        return {"username": username, "name": "", "fullname": ""}
    fullname = data.get("fullname") or data.get("name") or ""
    if not _names_match(candidate_name, fullname):
        return None
    return {
        "username": username,
        "name": data.get("name") or "",
        "fullname": fullname,
        "avatar": data.get("avatarUrl") or "",
    }


def find_semantic_scholar(candidate_name: str) -> dict | None:
    """Resolve the candidate to a Sem Scholar author by name search;
    we accept only when the top match has substantive output (>5 papers,
    >20 citations) so we don't blue-link a namesake graduate student."""
    url = (
        "https://api.semanticscholar.org/graph/v1/author/search"
        f"?query={urllib.parse.quote(candidate_name)}"
        "&limit=3&fields=name,affiliations,hIndex,citationCount,paperCount,homepage"
    )
    data = _http_json(url)
    if not data:
        return None
    for item in data.get("data") or []:
        nm = item.get("name") or ""
        if not _academic_name_match(candidate_name, nm):
            continue
        if int(item.get("paperCount") or 0) < 5:
            continue
        if int(item.get("citationCount") or 0) < 20:
            continue
        affs = item.get("affiliations") or []
        return {
            "authorId": item.get("authorId") or "",
            "name": nm,
            "affiliation": affs[0] if affs else "",
            "h_index": int(item.get("hIndex") or 0),
            "citations": int(item.get("citationCount") or 0),
            "papers": int(item.get("paperCount") or 0),
            "homepage": item.get("homepage") or "",
        }
    return None


def find_dblp(candidate_name: str) -> dict | None:
    """Top DBLP author hit by name search. We accept only when the
    name tokens overlap so we don't grab a homonym."""
    url = f"https://dblp.org/search/author/api?q={urllib.parse.quote(candidate_name)}&format=json&h=3"
    data = _http_json(url, headers={"Accept": "application/json"})
    if not data:
        return None
    hits = (((data.get("result") or {}).get("hits") or {}).get("hit")) or []
    for h in hits:
        info = h.get("info") or {}
        name = info.get("author") or ""
        if not _academic_name_match(candidate_name, name):
            continue
        url_ = info.get("url") or ""
        # Extract pid from URL: https://dblp.org/pid/12/3456.html
        m = re.search(r"/pid/([^/]+/[^.]+)", url_)
        pid = m.group(1) if m else ""
        return {"pid": pid, "name": name, "url": url_}
    return None


# ────────────────────────────────────────────────────────────────────
# Orchestrator
# ────────────────────────────────────────────────────────────────────


_OUT_COLS = [
    "handle",
    "name",
    "specialty",
    "github",
    "github_followers",
    "github_company",
    "huggingface",
    "scholar_id",
    "sem_scholar_id",
    "sem_scholar_h_index",
    "sem_scholar_citations",
    "dblp_pid",
    "affiliation",
    "website",
    "avatar",
    "bio",
]


def read_candidates(path: Path) -> list[dict]:
    rows: list[dict] = []
    for line in path.read_text().splitlines():
        if not line.strip():
            continue
        parts = line.split("\t")
        if len(parts) < 3:
            continue
        rows.append(
            {
                "handle": parts[0].strip(),
                "name": parts[1].strip(),
                "specialty": parts[2].strip(),
                "rationale": parts[3].strip() if len(parts) > 3 else "",
            }
        )
    return rows


def read_done(path: Path) -> set[str]:
    if not path.exists():
        return set()
    seen: set[str] = set()
    with path.open(encoding="utf-8") as f:
        r = csv.DictReader(f, delimiter="\t")
        for row in r:
            if row.get("handle"):
                seen.add(row["handle"].lower())
    return seen


def enrich_one(c: dict, api_key: str) -> dict:
    out = dict.fromkeys(_OUT_COLS, "")
    out["handle"] = c["handle"]
    out["name"] = c["name"]
    out["specialty"] = c["specialty"]

    # ONE Tavily call. Include the twitter handle so the search engine
    # disambiguates namesakes.
    query = f'"{c["name"]}" @{c["handle"]} github huggingface scholar'
    print(f"    tavily: {query}")
    results = tavily_search(query, api_key)
    parsed = extract_identifiers(results)
    src = parsed["sources"]

    if "github" in src:
        v = verify_github(src["github"]["id"], c["name"], c["handle"])
        if v:
            out["github"] = v["login"]
            out["github_followers"] = str(v["followers"])
            out["github_company"] = v["company"]
            if not out["avatar"]:
                out["avatar"] = v["avatar"]
            if v["blog"] and not out["website"]:
                out["website"] = v["blog"]
            if v["bio"] and not out["bio"]:
                out["bio"] = v["bio"]

    if "huggingface" in src:
        v = verify_huggingface(src["huggingface"]["id"], c["name"])
        if v:
            out["huggingface"] = v["username"]
            if v.get("avatar") and not out["avatar"]:
                out["avatar"] = v["avatar"]

    if "scholar" in src:
        out["scholar_id"] = src["scholar"]["id"]

    # Sem Scholar + DBLP by name — these have their own internal
    # name-match guard.
    ss = find_semantic_scholar(c["name"])
    if ss:
        out["sem_scholar_id"] = ss["authorId"]
        out["sem_scholar_h_index"] = str(ss["h_index"])
        out["sem_scholar_citations"] = str(ss["citations"])
        if ss["affiliation"] and not out["affiliation"]:
            out["affiliation"] = ss["affiliation"]
        if ss["homepage"] and not out["website"]:
            out["website"] = ss["homepage"]

    dblp = find_dblp(c["name"])
    if dblp:
        out["dblp_pid"] = dblp["pid"]

    # If we found a `dblp` URL via search too and the JSON API lookup
    # missed it (rare), keep the URL-derived pid as a fallback.
    if not out["dblp_pid"] and "dblp" in src:
        out["dblp_pid"] = src["dblp"]["id"]

    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--in",
        dest="inp",
        default="data/people/curated_ai_researchers_new.tsv",
        help="input TSV (handle, name, specialty, rationale)",
    )
    ap.add_argument(
        "--out",
        default="data/people/enriched_candidates.tsv",
        help="output TSV (incremental)",
    )
    ap.add_argument("--limit", type=int, default=0, help="stop after N candidates (0 = all)")
    args = ap.parse_args()

    api_key = os.environ.get("TAVILY_API_KEY")
    if not api_key:
        print("TAVILY_API_KEY missing in env — bailing.")
        return 1

    repo_root = Path(__file__).resolve().parent.parent
    in_path = (repo_root / args.inp).resolve()
    out_path = (repo_root / args.out).resolve()
    out_path.parent.mkdir(parents=True, exist_ok=True)

    candidates = read_candidates(in_path)
    done = read_done(out_path)
    todo = [c for c in candidates if c["handle"].lower() not in done]
    if args.limit:
        todo = todo[: args.limit]
    print(f"Reading {in_path}: {len(candidates)} candidates; {len(done)} already done; {len(todo)} to process.\n")

    # Open output in append mode, write header if file is new.
    new_file = not out_path.exists()
    with out_path.open("a", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=_OUT_COLS, delimiter="\t")
        if new_file:
            w.writeheader()
            f.flush()
        for i, c in enumerate(todo, 1):
            print(f"[{i}/{len(todo)}] @{c['handle']:<24} {c['name']}")
            try:
                row = enrich_one(c, api_key)
            except KeyboardInterrupt:
                raise
            except Exception as e:
                print(f"    ! enrich failed: {e}")
                row = dict.fromkeys(_OUT_COLS, "")
                row["handle"] = c["handle"]
                row["name"] = c["name"]
                row["specialty"] = c["specialty"]
            w.writerow(row)
            f.flush()
            filled = sum(1 for k, v in row.items() if v and k not in ("handle", "name", "specialty"))
            print(f"    ✓ {filled} fields filled")
            # Polite pacing — Tavily and the keyless APIs both handle
            # 1 req/s easily; this keeps us well below any rate limit.
            time.sleep(1.0)

    print(f"\n✓ done. Output: {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
